{
  "formatVersion": "1.1",
  "component": {
    "group": "pers.solid",
    "module": "brrp-fabric",
    "version": "1.0.4-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brrp-fabric-1.0.4-1.21.1.jar",
          "url": "brrp-fabric-1.0.4-1.21.1.jar",
          "size": 200631,
          "sha512": "0e11be8600ebe486322f441e895f034fa4de3bf2c11b502979abc08cb029018900c65e45d335f9214b3cae8f2dbeb6a995cdd699de499cb98c9908ade612f17f",
          "sha256": "92eeaa68eb22020a1de1d0cba1e50c4eb7dbb0d31dbdfb98d833923bdee31ecd",
          "sha1": "da2ac8ced9d62f05f9b93f21549d2f927ae9f4e1",
          "md5": "1445275f0fe7fe0e99dcbc7874c348a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.1+1.21.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "brrp-fabric-1.0.4-1.21.1.jar",
          "url": "brrp-fabric-1.0.4-1.21.1.jar",
          "size": 200631,
          "sha512": "0e11be8600ebe486322f441e895f034fa4de3bf2c11b502979abc08cb029018900c65e45d335f9214b3cae8f2dbeb6a995cdd699de499cb98c9908ade612f17f",
          "sha256": "92eeaa68eb22020a1de1d0cba1e50c4eb7dbb0d31dbdfb98d833923bdee31ecd",
          "sha1": "da2ac8ced9d62f05f9b93f21549d2f927ae9f4e1",
          "md5": "1445275f0fe7fe0e99dcbc7874c348a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brrp-fabric-1.0.4-1.21.1-sources.jar",
          "url": "brrp-fabric-1.0.4-1.21.1-sources.jar",
          "size": 37578,
          "sha512": "77eb02b1789ab8e545e54d35a8309aac1c21b83df35c20f374a4ce2f683c8ee6ec2b419a29e50fc3abed8b71ee55fccbd830d1420c95b604a9b2978164c5aacc",
          "sha256": "d4366d8c20b6874d59350ceafabf7dc35ec088f0eadccf1e99e2aa1f56b80f58",
          "sha1": "be2153bef03360dd7e289e6338433a52eaf1fd90",
          "md5": "82e2ae875308e62c698bb0c6933e5ddd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brrp-fabric-1.0.4-1.21.1-dev-shadow.jar",
          "url": "brrp-fabric-1.0.4-1.21.1-dev-shadow.jar",
          "size": 198379,
          "sha512": "fcaa2e55be2b1643e591e791a6993b09c715fea343cca35781965a484af17da222da3c445522cbdcb1406e97b7b0d331c4a4d4ad597b480d39cf1151b677474b",
          "sha256": "073fa355b0c2f5df6c736246927437292328db01832f999237d2f2eb880372a0",
          "sha1": "05ca3875fb79d554ab6bfa347b888f95ae7f6587",
          "md5": "f294e81c1a850f60734e933fe903ad06"
        }
      ]
    }
  ]
}
