{
  "formatVersion": "1.1",
  "component": {
    "group": "pers.solid",
    "module": "brrp-fabric",
    "version": "0.8.2-1.19.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brrp-fabric-0.8.2-1.19.3.jar",
          "url": "brrp-fabric-0.8.2-1.19.3.jar",
          "size": 251424,
          "sha512": "d3f3206f33ad5fade502afae2dbd031a4f087de5062f4d19155441790a3a8a285c76fc210b559a293b20c7638214920d945b316de455b3521b5db8f33b95953f",
          "sha256": "b1090f50a5eb4e1ccabab77436b4d26a350403e1c26e9610ff8c2c399b46ee1f",
          "sha1": "9c5c1822dc52055de035ebbade1fe0a8d43232cc",
          "md5": "284bd8dca1b6854caff547af72476a77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.68.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "brrp-fabric-0.8.2-1.19.3.jar",
          "url": "brrp-fabric-0.8.2-1.19.3.jar",
          "size": 251424,
          "sha512": "d3f3206f33ad5fade502afae2dbd031a4f087de5062f4d19155441790a3a8a285c76fc210b559a293b20c7638214920d945b316de455b3521b5db8f33b95953f",
          "sha256": "b1090f50a5eb4e1ccabab77436b4d26a350403e1c26e9610ff8c2c399b46ee1f",
          "sha1": "9c5c1822dc52055de035ebbade1fe0a8d43232cc",
          "md5": "284bd8dca1b6854caff547af72476a77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brrp-fabric-0.8.2-1.19.3-sources.jar",
          "url": "brrp-fabric-0.8.2-1.19.3-sources.jar",
          "size": 178313,
          "sha512": "ddc838c42e7cfc118dcfbb616958aada419044b6e895d72568f45444a8bfa1a891d0b2f0e5689872cb59cefdd89b18f1eff06a8b393cb8cadb42c20ed9d7aff5",
          "sha256": "531d8fbab305feb9c1dcb3a3be08bd5e51be0c122eb5f25cd0450a152390be08",
          "sha1": "43b9c78c2eec3cb1446bcaa5fbf49b7e0622a60a",
          "md5": "00542185233d018741ca5e1663a3fb69"
        }
      ]
    }
  ]
}
