{
  "formatVersion": "1.1",
  "component": {
    "group": "pers.solid",
    "module": "brrp",
    "version": "1.0.3-1.20.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brrp-1.0.3-1.20.6.jar",
          "url": "brrp-1.0.3-1.20.6.jar",
          "size": 194696,
          "sha512": "4d6b4c9abc13d4c39ad509320949c52b579a90b80baa1e864080d1de90663a4e4a8296cc0754e0126744cfaa06639b2e45edf3d8f9ec6f969e15849145f58234",
          "sha256": "1997551f7694980ba85f47c7ef62bef88db77d228982430049830b93238afc74",
          "sha1": "b086e4a6654c02fdf712d45e22156c22ff16a91f",
          "md5": "0c920e4a25f7d4751071662f92110fdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.98.0+1.20.6"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "10.0.0-beta.1"
          }
        }
      ],
      "files": [
        {
          "name": "brrp-1.0.3-1.20.6.jar",
          "url": "brrp-1.0.3-1.20.6.jar",
          "size": 194696,
          "sha512": "4d6b4c9abc13d4c39ad509320949c52b579a90b80baa1e864080d1de90663a4e4a8296cc0754e0126744cfaa06639b2e45edf3d8f9ec6f969e15849145f58234",
          "sha256": "1997551f7694980ba85f47c7ef62bef88db77d228982430049830b93238afc74",
          "sha1": "b086e4a6654c02fdf712d45e22156c22ff16a91f",
          "md5": "0c920e4a25f7d4751071662f92110fdc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brrp-1.0.3-1.20.6-sources.jar",
          "url": "brrp-1.0.3-1.20.6-sources.jar",
          "size": 37634,
          "sha512": "11666392e65ab8ef7dd0f5c767588afc458b34c0b5ec6bb0dab62a69ef41fd5d76dbb72aec2d1251cb73d95f41394fa5bfd2638d840c197f3ce0cc86c7c84093",
          "sha256": "f180609ed1153d29e08fe29b0bf556cbc85d378a9b888bbdf67e61acccc01da3",
          "sha1": "7a36fb0ae70e4df06353a4f3635a9ba440df6f79",
          "md5": "e64d0cbf8f3bb7df26df6dda8da790c2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brrp-1.0.3-1.20.6-dev-shadow.jar",
          "url": "brrp-1.0.3-1.20.6-dev-shadow.jar",
          "size": 192799,
          "sha512": "555b7ed97697596eaa83390d6f2ad1d26d061b546ba23974154fa8f5c520850b5b1bf3a57bbfa2b9ecb46e979dd5ece3de159abf04cf7bff7aa34ade261ba612",
          "sha256": "326bfa87b1471a10d79ec80dc9a42bb8adc47e60aa95be8ecb804cc2135cc510",
          "sha1": "6f1cfc61d55e59f9a8a5b88f6a7b4c5c6e3d75a2",
          "md5": "11149c3b1bb3a33b3aac722f1423849b"
        }
      ]
    }
  ]
}
